version: '3'

# https://github.com/felipewom/docker-compose-postgres/blob/main/docker-compose.yml
services:
  db-postgres:
    container_name: postgres
    image: postgres:16.2-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data/
    networks:
      - postgres-network
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "${POSTGRES_DB}"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 10s

  web:
    container_name: backend
    build: .
    restart: always
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
    ports:
      - "80:8000"
    depends_on:
      db-postgres:
        condition: service_healthy
    networks:
      - postgres-network
    healthcheck:
      test: ["CMD-SHELL", "curl", "http://0.0.0.0:8000/test"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 20s

networks:
  postgres-network:
    driver: bridge
volumes:
  db-data:
