version: '3'

# https://github.com/felipewom/docker-compose-postgres/blob/main/docker-compose.yml
services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    volumes:
      - db-data:/var/lib/postgresql/data/
    networks:
      - postgres-network
    ports:
      - "5432:5432"

  web:
    container_name: backend
    build: .
    ports:
      - "80:8000"
    depends_on:
      - db
    networks:
      - postgres-network


networks:
  postgres-network:
    driver: bridge
volumes:
  db-data:
