name: CI - Deploy

on:
  push:
    tags:
      - v[0-9]+

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build --tag  .
